nome=input("digiti nome da sua empresa")
tempo=int(input("quanto tempo tem sua empressa"))
faturamento=float(input("digite faturamento da empresa"))
print("nome da empresa:" + nome)
print("tempo de empresa:", tempo)
print("faturamento da empresa:",faturamento)
